import { writeFile } from "fs/promises";
import { getDeclarations } from "./processFile.js";
import { createMediaStyle } from "./styles.js";

export async function generateOutputCSS(config) {
  const cache = {};
  const declarations = getDeclarations();
  console.log(declarations);
  Object.keys(declarations).map((file) => {
    Object.keys(declarations[file]).forEach(async (label) => {
      try {
        createMediaStyle(config, label, declarations[file][label], cache);
      } catch (err) {
        console.error(`Error generating media query for label ${label} in file ${file}: ${err}`);
      }
    });
  });
  const result = Object.keys(cache)
    .map((label) => cache[label].mq.toString())
    .join("\n");
  await writeFile(
    config.output,
    `/* ForgeCSS autogenerated file */\n${result}`,
    "utf-8"
  );
}